spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jwt?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    hibernate:
      ddl-auto: create
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: "hello? i am secret key. hahaha i am so happy. what a beautiful day."
  access-token-validity-in-seconds: 43200 # 12 hours
  refresh-token-validity-in-seconds: 604800 # 1 week